"""Initial Migration

Revision ID: 60201bd3735d
Revises: 
Create Date: 2024-06-20 16:45:24.725758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60201bd3735d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note')
    # ### end Alembic commands ###
